service: edulyte-client-api
frameworkVersion: "3"
configValidationMode: error

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: Edulyte.wsgi.application
    packRequirements: false

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-southeast-2
  iam:
    role: 
      statements:
        - Effect: "Allow"
          Action:
          - s3:GetObject
          - s3:PutObject
          Resource: "arn:aws:s3:::*"

functions:
  app:
    handler: Edulyte.wsgi.application
    events:
      - http:
          path: /
          method: ANY

package:
  individually:
    true
  patterns:
    - ".env"
    - "!.git/**"
    - "!.github/**"
    - "!.serverless/**"
    - "!static/**"
    - "!.cache/**"
    - "!.pytest_cache/**"
    - "!node_modules/**"
    - "!venv/**"